### PR TITLE
Project setup

### PR DESCRIPTION
**Pull request by Berkay-akbas**
## Initial project setup
- Created file structure with webpack
- Jest library installed
- Setup linterns

### CODE REVIEW

**Comment by gak92** [comment]
Hi @Berkay-akbas ,
You did a great job so far 👏🏼 👏🏼
There are some issues that you still need to work on to go to the next project but you are almost there!
To highlight 💪🏻
Gitflow was correctly used. ✔️
👍 Good job!

STATUS: CHANGES REQUESTED ♻️
- Linter's test did not pass.
- Could not find the files for the corresponding Linters test.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏 💻
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please ping me @BenMukebo when you comment so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

**Comment by Berkay-akbas** [comment]
Hello Ali! 👋 
Lighthouse is still failing, at first, I added a CSS code to change the background to just test if the Webpack working.  I thought that was the reason for the failure but it is still failing after changing it. What are your thoughts?

**Comment by Berkay-akbas** [comment]
Hello @gak92,
After adding a dummy text problem went away 👍 . Ready for a second review!

**Comment by gak92** [comment]
Hi @Berkay-akbas , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✅ 
- Gitflow was used correctly 🚀 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
